---

name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: ci

    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x, 14.x, 12.x, 10.x]
        database-type: [postgres, mysql, mssql, sqlite]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          always-auth: false
          node-version: ${{ matrix.node-version }}

      - name: Start Database(s)
        run: |
          docker-compose \
            --file "scripts/docker-compose.yml" \
            up \
              --detach \
              --build \
              "${{ matrix.database-type }}"
        if: matrix.database-type != 'sqlite'

      - name: Initialize Database(s)
        run: |
          docker-compose \
            --file "scripts/docker-compose.yml" \
            up \
              --detach \
              "wait${{ matrix.database-type }}"
        if: matrix.database-type != 'sqlite'

      - name: Run npm install
        run: npm install

      - name: Run Tests
        run: npm run test
        env:
          CI: true
          DB: ${{ matrix.database-type }}

      - name: Stop Database(s)
        run: |
          docker-compose \
            --file "scripts/docker-compose.yml" \
            down
        if: matrix.database-type != 'sqlite'

  automerge:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: fastify/github-action-merge-dependabot@v3.1.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
